# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xbuf/materials.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import xbuf.primitives_pb2

from xbuf.primitives_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='xbuf/materials.proto',
  package='xbuf',
  serialized_pb=_b('\n\x14xbuf/materials.proto\x12\x04xbuf\x1a\x15xbuf/primitives.proto\"\x98\x01\n\x0bMatProperty\x12\n\n\x02id\x18\x01 \x02(\t\x12\x1a\n\x05\x63olor\x18\x02 \x01(\x0b\x32\x0b.xbuf.Color\x12\x1e\n\x07texture\x18\x03 \x01(\x0b\x32\r.xbuf.Texture\x12\r\n\x05value\x18\x04 \x01(\x01\x12\x18\n\x04vec2\x18\x05 \x01(\x0b\x32\n.xbuf.Vec2\x12\x18\n\x04vec3\x18\x06 \x01(\x0b\x32\n.xbuf.Vec3\"[\n\x08Material\x12\n\n\x02id\x18\x01 \x02(\t\x12\x0e\n\x06mat_id\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\x12%\n\nproperties\x18\x05 \x03(\x0b\x32\x11.xbuf.MatPropertyP\x00')
  ,
  dependencies=[xbuf.primitives_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MATPROPERTY = _descriptor.Descriptor(
  name='MatProperty',
  full_name='xbuf.MatProperty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='xbuf.MatProperty.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='color', full_name='xbuf.MatProperty.color', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='texture', full_name='xbuf.MatProperty.texture', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='xbuf.MatProperty.value', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vec2', full_name='xbuf.MatProperty.vec2', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vec3', full_name='xbuf.MatProperty.vec3', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=206,
)


_MATERIAL = _descriptor.Descriptor(
  name='Material',
  full_name='xbuf.Material',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='xbuf.Material.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mat_id', full_name='xbuf.Material.mat_id', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='xbuf.Material.name', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='properties', full_name='xbuf.Material.properties', index=3,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=208,
  serialized_end=299,
)

_MATPROPERTY.fields_by_name['color'].message_type = xbuf.primitives_pb2._COLOR
_MATPROPERTY.fields_by_name['texture'].message_type = xbuf.primitives_pb2._TEXTURE
_MATPROPERTY.fields_by_name['vec2'].message_type = xbuf.primitives_pb2._VEC2
_MATPROPERTY.fields_by_name['vec3'].message_type = xbuf.primitives_pb2._VEC3
_MATERIAL.fields_by_name['properties'].message_type = _MATPROPERTY
DESCRIPTOR.message_types_by_name['MatProperty'] = _MATPROPERTY
DESCRIPTOR.message_types_by_name['Material'] = _MATERIAL

MatProperty = _reflection.GeneratedProtocolMessageType('MatProperty', (_message.Message,), dict(
  DESCRIPTOR = _MATPROPERTY,
  __module__ = 'xbuf.materials_pb2'
  # @@protoc_insertion_point(class_scope:xbuf.MatProperty)
  ))
_sym_db.RegisterMessage(MatProperty)

Material = _reflection.GeneratedProtocolMessageType('Material', (_message.Message,), dict(
  DESCRIPTOR = _MATERIAL,
  __module__ = 'xbuf.materials_pb2'
  # @@protoc_insertion_point(class_scope:xbuf.Material)
  ))
_sym_db.RegisterMessage(Material)


# @@protoc_insertion_point(module_scope)
